"""
Django settings for askcompany project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*(%d#$g&boe@$(r1(1vn22en$9r-+5j@61ge!09534kwz0$tj3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third apps
    'django_extensions',
    'debug_toolbar',
    'bootstrap4',

    # local apps
    'blog1',
    'instagram',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'askcompany.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # File System Template Loader
            # 만약 templates의 경로를 앱/templates/으로 만들어주고 싶다면
            # os.path.join(BASE_DIR, 'app_name', 'templates')
            # 이렇게 해주면 된다.
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'askcompany.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = '' # will be

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 이거는 url에 접근할때 사용해주는 경로다
# 이를테면 이게 '/data/'라고 되어있다면 localhost:8000/data/ 이렇게 가는거다.
MEDIA_URL = '/media/'

# BASE_DIR 밑에 있는 media라는 곳에다가 media를 저장하겠다. 라는 의미
# 그리고 여기서 지정된 폴더중에서 없는 폴더는 다 만들어준다.
# 지금 여기의 경우네는 BASE_DIR이라는 기준이되는 폴더와 그 하위로 media라고 2개의 폴더로 이루어진 구조지만
# BASE_DIR과 media 사이에 '..'를 둔다던지 'public'등을 두게되면 그 두게된 경로 명령에 따라서
# 없는것은 생성된다.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# debug_toolbar area
# debug_toolbar는 templates에 body태그가 있어야만 동작한다.
INTERNAL_IPS = [
    "127.0.0.1",
]

# User를 설정할 경우
# 해당 유저모델이 있는 앱이름.모델이름 을 적어주면 된다.
# 프로젝트 생성하자마자 해주는게 좋다.
# AUTH_USER_MODEL = 'auth.User'
